### ISSUE TITLE
Incorporating Mutual Information for EDA

### ISSUE THREAD

**Issue by HridayM25** [ThomasMeissnerDS/BlueCast#31]
Mutual Information (MI) is a very useful tool for Feature Engineering. The MI between two quantities is a measure of the extent to which knowledge of one quantity reduces uncertainty about the other. I believe it can be helpful if we can have MI with BlueCast.

**Comment by ThomasMeissnerDS** [comment]
Thanks for pointing this out. I will check it out. Do you have good resources about this?

**Comment by ThomasMeissnerDS** [comment]
Okay, I took a quick look. This looks interesting indeed. I might add this to the 0.70 release which is on the way. Will see

**Comment by HridayM25** [comment]
Sure, let me know if I can be of any help!

I'll provide a good resource here : 
https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.kaggle.com/code/ryanholbrook/mutual-information&ved=2ahUKEwi9u5KQ3q-CAxVXa2wGHe3fAdYQFnoECAgQAQ&usg=AOvVaw3B_Ok6GYT4MTplOVVdqjvj

**Comment by ThomasMeissnerDS** [comment]
Here you can see the implementation:
https://github.com/ThomasMeissnerDS/BlueCast/blob/0105706421e7d6d67a16c6a3662a658ec7d13f61/bluecast/eda/analyse.py#L295

This shows a bar plot in descending order for the MI scores towards the target variable.

**Comment by ThomasMeissnerDS** [comment]
The PR has been merged and version 0.70 has been released including MI score plot. Closing the issue. If you need anything else please let us know.
