### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Kkhurana007** [ThomasMeissnerDS/BlueCast#36]
unable to install it on Pyton 3.12.

can you fix this? or help me to install? 
![image](https://github.com/ThomasMeissnerDS/BlueCast/assets/91566244/a6e421c4-484e-411d-9395-3ea53f450b90)

**Comment by ThomasMeissnerDS** [comment]
Hi,

thanks for reaching out. Currently the libraray is pinned up until Python 3.11 (see in the [toml](https://github.com/ThomasMeissnerDS/BlueCast/blob/48667ed300580ccffada62ce81ea00e20de9f243/pyproject.toml#L20))

In release 0.90 (next release I will include Python 3.12 as well ([PR](https://github.com/ThomasMeissnerDS/BlueCast/pull/35)).
If you want to test it until then, you could do the following steps:
* clone the repo
* change the Python dependency to also cover 3.12
* create a conda env: `conda create -n "env_name"`
* in that conda env: `pip install poetry`
* then: `poetry install`

Then you should be able to run BlueCast in the env.

**Comment by ThomasMeissnerDS** [comment]
In the PR itself I added Python 3.12 and the wheels (under dist folder) are updated already. So you could also download them and install from wheel to bridge the time until BlueCast 0.90 is out.

**Comment by Kkhurana007** [comment]
Thank you, Thomas, for your explanation. While I couldn't use the BlueCast with the provided instructions, I will attempt it later.

**Comment by ThomasMeissnerDS** [comment]
Feel free to open a new issue.The new release should be a matter of days only though.

**Comment by Kkhurana007** [comment]
Sure! thanks again!

**Comment by ThomasMeissnerDS** [comment]
BlueCast 0.90 released. Let me know in case you face any issues on Python 3.12
