### ISSUE TITLE
if you plan to incorporate functionality for multi-label tasks into Bluecast?

### ISSUE THREAD

**Issue by yangfa-zhang** [ThomasMeissnerDS/BlueCast#41]

**Comment by thomasmeissnercrm** [comment]
Hi @yangfa-zhang !

So far I did not have any particular plans. Could you elaborate what exactly you would need?
* Would be a non-CV (aka single model) instance be sufficient?
* Do you have a small example dataset at hand for testing purposes?

**Comment by yangfa-zhang** [comment]
Hi @thomasmeissnercrm !
I noticed that in class_problem there are only options for binary, multi-class, and regression. For instance, if we have a dataset where we want to predict both the type of fruit (multi-class) and its weight (regression), the current options in Bluecast might not suffice. Can we include models in Bluecast that can predict multiple variables?

**Comment by ThomasMeissnerDS** [comment]
From what you describe it sounds like you would like to get the class scores of all classs in a multiclass problem. When using `BlueCast `class, you get the class scores of all classes.

With `BlueCastCV ` you can specify `return_sub_models_preds=True` to receive class scores of all classs.

You can see this in the following [overview notebook](https://www.kaggle.com/code/thomasmeiner/ps4e3-bluecast-a-comprehensive-overview#The-multiple-faces-of-BlueCast) as part of a multiclass kaggle competition.

Is that what you are looking for?

**Comment by yangfa-zhang** [comment]
thanks！ @ThomasMeissnerDS
